package com.rahul100ni.tether.ui.theme

import androidx.compose.ui.graphics.Color

// Dark scheme — green/teal brand palette
val DarkPrimary = Color(0xFF67DBAF)
val DarkOnPrimary = Color(0xFF003828)
val DarkPrimaryContainer = Color(0xFF005139)
val DarkOnPrimaryContainer = Color(0xFF84F8CB)
val DarkSecondary = Color(0xFFB2CCBF)
val DarkOnSecondary = Color(0xFF1E352A)
val DarkSecondaryContainer = Color(0xFF344B40)
val DarkOnSecondaryContainer = Color(0xFFCEE9D9)
val DarkBackground = Color(0xFF0F1510)
val DarkOnBackground = Color(0xFFDEE4DE)
val DarkSurface = Color(0xFF0F1510)
val DarkOnSurface = Color(0xFFDEE4DE)
val DarkSurfaceVariant = Color(0xFF3C4940)
val DarkOnSurfaceVariant = Color(0xFFBBC9C1)
val DarkOutline = Color(0xFF859E94)
val DarkOutlineVariant = Color(0xFF3C4940)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Light scheme
val LightPrimary = Color(0xFF006C44)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF8FF8C2)
val LightOnPrimaryContainer = Color(0xFF002113)
val LightSecondary = Color(0xFF4D6B59)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE9D6)
val LightOnSecondaryContainer = Color(0xFF09271A)
val LightBackground = Color(0xFFF5FBF5)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFF5FBF5)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDAE5DB)
val LightOnSurfaceVariant = Color(0xFF3F4942)
val LightOutline = Color(0xFF6F796F)
val LightOutlineVariant = Color(0xFFBEC9BE)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
